### ISSUE TITLE
Participants field should be a radio buttons

### ISSUE THREAD

**Issue by elisechant** [CodeforAustralia/cese-snippet#159]
UPDATE: Change "Number of Participants" from text field to radio rather than slider. 
Its more practical to select a small set of fixed range.

See sample:
![image](https://user-images.githubusercontent.com/33475160/39845184-c2b8ea92-5437-11e8-9cf6-cb3755b31358.png)

Ranges values are are:
<30, 30-100, 101-200, 201-500, >500

1. A range slider field component
2. Switch participants field to be a range slider (particular range values not known - check with Claramae)

Possible candidates from a quick search:
https://www.npmjs.com/package/rc-slider
https://www.npmjs.com/package/react-simple-range

**Comment by skumo** [comment]
I'm looking into this.

**Comment by clarasg** [comment]
@skumo I've updated the requirement for this. Details up in first comment
